#!/usr/bin/env node
/**
 * TinyLang Playground Build Script
 * 
 * Bundles the TinyLang engine (src/index.ts) into a single IIFE JS blob
 * and injects it into the template.html to produce the final index.html.
 */

const esbuild = require('esbuild');
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const TEMPLATE = path.join(__dirname, 'template.html');
const OUTPUT = path.join(__dirname, 'index.html');
const ENTRY = path.join(ROOT, 'src', 'index.ts');

async function build() {
  console.log('Building TinyLang playground...');

  // Bundle the engine
  const result = await esbuild.build({
    entryPoints: [ENTRY],
    bundle: true,
    format: 'iife',
    globalName: 'TinyLangBundle',
    platform: 'browser',
    target: 'es2020',
    write: false,
    minify: false, // Keep readable for debugging
    define: {
      'process.env.NODE_ENV': '"production"',
      'process.argv': '[]',
      'process.exit': '(function(){})',
      'process.stdout': '({write:function(){}})',
      'process.stderr': '({write:function(){}})',
    },
    external: ['fs', 'path', 'readline-sync', 'readline', 'child_process'],
  });

  const engineBundle = result.outputFiles[0].text;

  // Create the wrapper that exposes globals
  const wrappedBundle = `
// TinyLang Engine Bundle - Auto-generated by playground/build.js
(function() {
${engineBundle}

// Expose classes globally for the playground
window.TinyLang = TinyLangBundle.TinyLang;
window.TinyLangLexer = TinyLangBundle.Lexer;
window.TinyLangParser = TinyLangBundle.Parser;
window.TinyLangInterpreter = TinyLangBundle.Interpreter;
window.TinyLangCompiler = TinyLangBundle.Compiler;
window.TinyLangVM = TinyLangBundle.VM;
window.TinyLangFormatter = TinyLangBundle.Formatter;
window.TinyLangLinter = TinyLangBundle.Linter;
window.TinyLangTestRunner = TinyLangBundle.TestRunner;
window.TinyLangDebugger = TinyLangBundle.Debugger;
window.TinyLangChunk = TinyLangBundle.Chunk;
window.TinyLangOpCode = TinyLangBundle.OpCode;
window.TinyLangDisassemble = TinyLangBundle.disassemble;
window.TinyLangOptimize = TinyLangBundle.optimize;
window.TinyLangBundle = TinyLangBundle;
})();
`;

  // Read template
  if (!fs.existsSync(TEMPLATE)) {
    console.error('Error: template.html not found at', TEMPLATE);
    process.exit(1);
  }

  const template = fs.readFileSync(TEMPLATE, 'utf-8');

  // Inject bundle
  const finalHtml = template.replace('{{ENGINE_BUNDLE}}', wrappedBundle);

  // Write output
  fs.writeFileSync(OUTPUT, finalHtml, 'utf-8');

  const sizeKB = Math.round(fs.statSync(OUTPUT).size / 1024);
  console.log(`Done! Output: ${OUTPUT} (${sizeKB} KB)`);
}

build().catch(err => {
  console.error('Build failed:', err);
  process.exit(1);
});
